// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Verso.Core.Data;

#nullable disable

namespace Verso.Core.Data.Migrations
{
    [DbContext(typeof(VersoDbContext))]
    partial class VersoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("TagTranscription", b =>
                {
                    b.Property<int>("TagsId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TranscriptionId")
                        .HasColumnType("TEXT");

                    b.HasKey("TagsId", "TranscriptionId");

                    b.HasIndex("TranscriptionId");

                    b.ToTable("TranscriptionTag", (string)null);
                });

            modelBuilder.Entity("Verso.Core.Data.Entities.Folder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ColorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ResearchPages", (string)null);
                });

            modelBuilder.Entity("Verso.Core.Data.Entities.Segment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("EndSeconds")
                        .HasColumnType("REAL");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("SpeakerId")
                        .HasColumnType("TEXT");

                    b.Property<double>("StartSeconds")
                        .HasColumnType("REAL");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TranscriptionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SpeakerId");

                    b.HasIndex("TranscriptionId");

                    b.ToTable("Segments", (string)null);
                });

            modelBuilder.Entity("Verso.Core.Data.Entities.Speaker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TranscriptionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TranscriptionId");

                    b.ToTable("Speakers", (string)null);
                });

            modelBuilder.Entity("Verso.Core.Data.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ColorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags", (string)null);
                });

            modelBuilder.Entity("Verso.Core.Data.Entities.Transcription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Device")
                        .HasColumnType("INTEGER");

                    b.Property<double>("DurationSeconds")
                        .HasColumnType("REAL");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FolderId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ResearchPageId");

                    b.Property<string>("Icon")
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaFilePath")
                        .HasColumnType("TEXT");

                    b.Property<double?>("ProcessingDurationSeconds")
                        .HasColumnType("REAL");

                    b.Property<int>("Quality")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpeakerMode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FolderId");

                    b.HasIndex("Status");

                    b.ToTable("Transcriptions", (string)null);
                });

            modelBuilder.Entity("Verso.Core.Data.Entities.UserSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DarkTheme")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefaultLanguage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DefaultQuality")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Device")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IdentifySpeakersDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("LiveTranscriptionEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxTranscriptionThreads")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserSettings", (string)null);
                });

            modelBuilder.Entity("TagTranscription", b =>
                {
                    b.HasOne("Verso.Core.Data.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Verso.Core.Data.Entities.Transcription", null)
                        .WithMany()
                        .HasForeignKey("TranscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Verso.Core.Data.Entities.Segment", b =>
                {
                    b.HasOne("Verso.Core.Data.Entities.Speaker", "Speaker")
                        .WithMany()
                        .HasForeignKey("SpeakerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Verso.Core.Data.Entities.Transcription", null)
                        .WithMany("Segments")
                        .HasForeignKey("TranscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Speaker");
                });

            modelBuilder.Entity("Verso.Core.Data.Entities.Speaker", b =>
                {
                    b.HasOne("Verso.Core.Data.Entities.Transcription", null)
                        .WithMany("Speakers")
                        .HasForeignKey("TranscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Verso.Core.Data.Entities.Transcription", b =>
                {
                    b.HasOne("Verso.Core.Data.Entities.Folder", "Folder")
                        .WithMany("Transcriptions")
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Folder");
                });

            modelBuilder.Entity("Verso.Core.Data.Entities.Folder", b =>
                {
                    b.Navigation("Transcriptions");
                });

            modelBuilder.Entity("Verso.Core.Data.Entities.Transcription", b =>
                {
                    b.Navigation("Segments");

                    b.Navigation("Speakers");
                });
#pragma warning restore 612, 618
        }
    }
}
